# Lab 1  : Basics of Tensorflow

## Importing Tensorflow and print Hello World!

In [1]:
import tensorflow as tf

Save "Hello Tensorflow!!" to the constant variable hello

In [2]:
hello = tf.constant('Hello Tensorflow!!')     #assignment 

Print this constant variable hello

In [3]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


It can be seen that the content "Hello Tensorflow!!" is not printed but only the format of the output tensor. 
This is because the operation of assigning a string value to the hello variable is defined (as a graph), but the operation is not performed yet. 

Here ":0" in "Const:0" means the 'output'. The shape of the output is 1 dimension, and the type(dtype) is of  string type.

To perform the assigning operation we have to open a session:

In [4]:
sess = tf.Session()

Using the Session sess, we can perform the assignment operation to the hello variable, and store the running result into the result variable.

In [5]:
result = sess.run(hello)

printing the result variable

In [6]:
print(result)

b'Hello Tensorflow!!'


## Types in Tensorflow

### The following has been adopted from the Blog of 조대협(http://bcho.tistory.com/1153) 

### Constant Type

Calculation in python:

In [7]:
x = 1
print(x)

1


In [8]:
y = x+9
print(y)

10


However, with the tensorflow library the operation becomes like this:

In [9]:
x = tf.constant(1,name = 'x')
print(x)

Tensor("x:0", shape=(), dtype=int32)


Open a Session and run the Session to get the value for x (stored in result) and print the value: 

In [10]:
sess = tf.Session()
result = sess.run(x)
print(result)

1


### Variables

Declare the variable y, and assign x+9 to it.

In [11]:
x = tf.constant(1,name = 'x')
y = tf.Variable(x+9,name = 'y') #variables are defined with Variable function.

Print the variable y. Only the type information gets printed.

In [12]:
print(y)

<tf.Variable 'y:0' shape=() dtype=int32_ref>


Open a Session and try to print out the output.

In [13]:
sess = tf.Session()
result = sess.run(y)
print(result)

FailedPreconditionError: Attempting to use uninitialized value y
	 [[Node: _retval_y_0_0 = _Retval[T=DT_INT32, index=0, _device="/job:localhost/replica:0/task:0/device:CPU:0"](y)]]

However, the above code results in error. This is because with variables the initializing of the variables have to be performed first.

In [15]:
sess = tf.Session()
init = tf.global_variables_initializer()  # define the initializing operation of all variables
sess.run(init)   # run the initializing operation. 
result = sess.run(y)
print(result) 

10


### Placeholders

Placeholders are places where we put in the training (or test) data. The data for the placeholders are feed at the run of the Session.

In [16]:
import tensorflow as tf
input_data = [1,2,3,4,5]
input_data2 = [3,5,7,9,11]

x = tf.placeholder(dtype=tf.float32)
y = x * 2  # y is not of Variables type. Therefore there is no need for initialization

sess = tf.Session()

result = sess.run(y,feed_dict={x:input_data})
print (result)

# Now changing the feeding data and run again.
result = sess.run(y,feed_dict={x:input_data2})  
print (result)

[ 2.  4.  6.  8. 10.]
[ 6. 10. 14. 18. 22.]


Try the same thing with W as a Variable. In this case, we have to perform the initialization of the variables

In [17]:
import tensorflow as tf
input_data = [1,2,3,4,5]
x = tf.placeholder(dtype=tf.float32)
W = tf.Variable([2],dtype=tf.float32) 
y = W*x

sess = tf.Session()

init =  tf.global_variables_initializer() 
sess.run(init)

result = sess.run(y,feed_dict={x:input_data})

print(result)

[ 2.  4.  6.  8. 10.]


## Practice #1 : Define your own operation and try to print the result out (10minutes)

In [3]:
## Practice #1

## Matrix

The following code is a multiplication of a  1x3 and a 3x1 constant vector.

![title](img/Day1-1-2.png)

In [18]:
import tensorflow as tf
x = tf.constant([ [1.0,2.0,3.0] ])        # 1x3 constant vector
print('Form of the x vector:')
print(x.get_shape())

w = tf.constant([ [2.0],[2.0],[2.0] ])    # 3x1 constant vector
print('Form of the w vector:')
print(w.get_shape())

y = tf.matmul(x,w)                        # Inner product of x and w vectors 

sess = tf.Session()
init = tf.global_variables_initializer()      #initializing the variables
sess.run(init)
result = sess.run(y)

print('The multiplication of x and w vectors:')
print(result)

Form of the x vector:
(1, 3)
Form of the w vector:
(3, 1)
The multiplication of x and w vectors:
[[12.]]


The following is a multiplication of a 3x3 and a 3x1 matrix.

![title](img/Day1-1-3.png)

The code is as follows:

In [19]:
import tensorflow as tf
input_data = [ [1.,2.,3.],[1.,2.,3.],[2.,3.,4.] ] #3x3 matrix
x = tf.placeholder(dtype=tf.float32,shape=[None,3])
w = tf.Variable([ [2.],[2.],[2.] ], dtype = tf.float32) #3x1 matrix
y = tf.matmul(x,w)

sess = tf.Session()

init =  tf.global_variables_initializer()  #Initializing the variable
sess.run(init)

result = sess.run(y,feed_dict={x:input_data})

print (result)

[[12.]
 [12.]
 [18.]]


The size of the above x matrix is defined as None x 3, Here None means 'any size', where the size for None is given at running time. Therefore  Nonex3 can be 1x3, 2x3, 3x3,....100x3 etc. according to what value is given for None at running time. 

In [20]:
import tensorflow as tf
input_data1 = [ [1.,2.,3.],[1.,2.,3.],[2.,3.,4.] ] #3x3 matrix
input_data2 = [[1.,2.,3.]] #1x3 matrix
x = tf.placeholder(dtype=tf.float32,shape=[None,3])
w = tf.Variable([ [2.],[2.],[2.] ], dtype = tf.float32) #3x1 matrix
y = tf.matmul(x,w)

sess = tf.Session()

init =  tf.global_variables_initializer()  # Initialize the variables
sess.run(init)

result1 = sess.run(y,feed_dict={x:input_data1})  # feed a 3x3 matrix
print (result1)

result2 = sess.run(y,feed_dict={x:input_data2}) # feed a 3x1 matrix
print(result2)

[[12.]
 [12.]
 [18.]]
[[12.]]


This is because we cannot know the exact size of the training data set, and therefore, have to make it flexible.

## Broadcasting

In [21]:
import tensorflow as tf
input_data = [
     [1,1,1],[2,2,2]
    ]
x = tf.placeholder(dtype=tf.float32,shape=[2,3])  # 2x3 matrix
w  =tf.Variable([[2],[2],[2]],dtype=tf.float32)  # 3x1 matrix
b  =tf.Variable([4],dtype=tf.float32)            # 1x1 matrix
y = tf.matmul(x,w)+b    # multiply 2x3 matrix with 3x1 matrix + 1x1 matrix : By broadcasing the size of the 1x1 matrix becomes 2x1 automatically1

print (x.get_shape())
sess = tf.Session()
init = tf.global_variables_initializer() 
sess.run(init)
result = sess.run(y,feed_dict={x:input_data})

print (result)

(2, 3)
[[10.]
 [16.]]


In the code above  x is a 2x3 matrix and  w is a 3x1 matrix. The multiplication of those two results in a 2x1 matrix. Then, b is added to the result, but since b is of size 1x1 the size doesn't match. In the above case the b matrix is automatically stretched to become of size 2x1. This is called broadcasting. Here, as the name 'broad' implies, the matrix can be stretched but not shrinked. In tensorflow, the rule for broadcasting follows the rule of broadcasting in numpy arrays.(http://scipy.github.io/old-wiki/pages/EricsBroadcastingDoc). For broadcasting to occur at least one of the dimensions should be the same, and one of the dimensions should be 1.

![title](img/broadcasting1.gif)

A two dimensional array multiplied by a one dimensional array results in broadcasting if number of 1-d array elements matches the number of 2-d array columns.

In [22]:
#import tensorflow as tf

a  =tf.Variable([[0,0,0],[10,10,10],[20,20,20],[30,30,30]],dtype=tf.float32)  # 4x3 matrix
b  =tf.Variable([[0,1,2]],dtype=tf.float32) # 1x4 matrix  
y  = a+b   # 4x3 matrix + 1x3 matrix --> by broadcasting 1x3 matrix is stretched to 4x3.
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)
result = sess.run(y)

print (result)

[[ 0.  1.  2.]
 [10. 11. 12.]
 [20. 21. 22.]
 [30. 31. 32.]]


Another example where broadcasting occurs for the columns:

In [23]:
import tensorflow as tf

a  =tf.Variable([[0,0,0],[10,10,10],[20,20,20],[30,30,30]],dtype=tf.float32)  # 4x3 matrix
b  =tf.Variable([[0],[0],[0],[0]],dtype=tf.float32) # 4x1 matrix 
y  = a+b   # 4x3 matrix + 4x1 matrix --> by broadcasting 4x1 matrix becomes 4x3 matrix

sess = tf.Session()
init = tf.global_variables_initializer() 
sess.run(init)
result = sess.run(y)

print (result)

[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]


![그림2](img/broadcasting2.gif)

When the trailing dimensions of the arrays are unequal, broadcasting fails because it is impossible to align the values in the rows of the 1st array with the elements of the 2nd arrays for element-by-element addition.

![title](img/broadcasting3.gif)

However, an exception is when both matrices are 1-d arrays. The above shows the case for the adding of a 4x1 matrix and a 1x3 matrix. This can be seen as an outer product of the matrices.
In this case, broadcasting stretches both arrays to form an output array larger than either of the initial arrays.

In [4]:
import tensorflow as tf

a  =tf.Variable([[0],[10],[20],[30]],dtype=tf.float32)  # 4x1 matrix
b  =tf.Variable([[0,1,2]],dtype=tf.float32) # 1x3 matrix
y  =a+b # 4x1 matrix + 1x3 matrix
        # by broadcasting:  4x1 matrix-> 4x3 matrix, 1x3 matrix-> 4x3 matrix.
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)
result = sess.run(y)

print (result)

[[  0.   1.   2.]
 [ 10.  11.  12.]
 [ 20.  21.  22.]
 [ 30.  31.  32.]]


## Practice #2 : Broadcasting practice

In [ ]:
## Practice #2